[package]
name = "nbt-rs"
version = "0.4.0"
authors = ["Aräjtav <arajtav@arajtav.com>"]
edition = "2024"
description = "A simple rust library for dealing with NBT"
repository = "https://github.com/Arajtav/nbt-rs"
license = "MIT"
keywords = ["nbt"]
categories = ["parser-implementations"]
exclude = ["/.git*", "/tests"]

[dependencies]
bytemuck = "1.23.1"
enum-as-inner = "0.6.1"
thiserror = "2.0"
