on: push
name: Run Tests

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: Swatinem/rust-cache@v2
              with:
                  shared-key: "rust-ci-cache"

            - name: Run Tests
              run: cargo test
